version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: totp
      POSTGRES_PASSWORD: totp
      POSTGRES_DB: totp
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring_network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    depends_on:
      - postgres  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/totp
      - SPRING_DATASOURCE_USERNAME=totp
      - SPRING_DATASOURCE_PASSWORD=totp
      - SPRING_EMAIL_USERNAME=populargjorgi@gmail.com
      - SPRING_EMAIL_PASSWORD=jhmy tayr lrqz wdao
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - spring_network

networks:
  spring_network:

volumes:
  db-data:
