name: CI_RO

on: # trigger event
  push: # event push
    branches: [main]

jobs:
  example: # name of job
    name: BUILD DOCKER IMAGE
    runs-on: ubuntu-latest # SO where jobs will execute.
    steps: # sequence tasks to do.
      - name: PULL REPOSITORY
        uses: actions/checkout@v2

      - name: USING ACTION TO BUILD AND PUST :)
        uses: NRO04/docker-build-push-action@v2
        with: #args for action, all of them are required.
          name-repository: ${{ secrets.DOCKERHUB_USERNAME }}/spring-app #repository name, specify what the repository will be called on dockerhub.
          tag: latest #tag for repository
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }} # docker account - username
          docker-password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} # docker password, it should use access token
         
